apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: html-page
        image: ghcr.io/sean-mcguinness/html-page:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: m210-page
  name: m210-page
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: m210-page
  name: m210-page
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: m210-page
  tls:
    termination: edge   
    insecureEdgeTerminationPolicy: Redirect
